---

- shell: hostname
  register: current_hostname

- name: Install MariaDB
  apt: name=mariadb-server state=present
  
- name: Install python-mysqldb
  apt: name=python-mysqldb state=present
  
- name: Copy across new mariadb config
  template:
    src=50-server.cnf.j2
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
  notify:
    - restart mariadb
    
- name: Ensure service is started
  service:
    name: mysql
    state: started
    enabled: yes
    
- name: mariadb-server | Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent 
  with_items:
    - localhost
    - "%"
    - "{{ current_hostname.stdout | lower }}"
    
- name: Create MySQL db for ecomm
  mysql_db: name={{ database }} state=present

- name: Create MySQL user for ecomm
  mysql_user: host={{ vagrant.private_host_ip }} name={{ user }} password={{ password }} priv={{ database }}.*:ALL state=present
  
#- name: mariadb-server | Update root password for all root accounts
#  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ root_password }} login_user=root login_password={{ root_password }}
#  with_items:
#    - "{{ current_hostname.stdout | lower }}"
#    - 127.0.0.1
#    - ::1
#    - localhost

#- name: Check if root password is set
#  shell: >
#    mysqladmin -u root status
#  changed_when: false
#  failed_when: false
#  register: root_pwd_check
#
#
#- name: Set MariaDB root password for the first time
#  mysql_user:
#    name: root
#    password: "{{ root_password }}"
#    host_all: yes
#    state: present
#  when: root_pwd_check.rc == 0


